In [1]:
import torch
x = torch.tensor(2.0, requires_grad = True)

In [2]:
y = x * 3 + x ** x
z = 2 * y + 1

In [3]:
z.backward()

In [4]:
print(x.grad)

tensor(14.)


In [5]:
with torch.no_grad():
    y = x*12

In [1]:
import torch

# Create a 2D tensor with requires_grad=True
X = torch.tensor([[2.0, 3.0], [4.0, 5.0]], requires_grad=True)
print(X)

tensor([[2., 3.],
        [4., 5.]], requires_grad=True)


In [2]:
# Define a function (for example, sum of squares of elements in X)
Y = X**2
print(Y)

tensor([[ 4.,  9.],
        [16., 25.]], grad_fn=<PowBackward0>)


In [3]:
# Compute the sum of all elements in Y (just for simplicity)
Z = Y.sum()
print(Z)

tensor(54., grad_fn=<SumBackward0>)


In [4]:
# Compute the gradients by calling backward
Z.backward()

# Print the gradient of X
print("Gradient of X:")
print(X.grad)

Gradient of X:
tensor([[ 4.,  6.],
        [ 8., 10.]])


In [5]:
X = torch.tensor([[2.0,3.0],[43.0,89.12]],requires_grad = True)
Y = X**2 + 3*X
Z = 2*Y
W = Z**3 + 3*Z

In [6]:
out = W.sum()
print(out)

tensor(4.4886e+12, grad_fn=<SumBackward0>)


In [7]:
out.backward()
print(X.grad)

tensor([[1.6842e+04, 7.0038e+04],
        [8.3571e+09, 2.9317e+11]])


In [10]:
"""
W.backward()
print(X.grad)
"""
"The above will throw and error as Gradient in PyTorch is calculated using Scalers"

'The above will throw and error as Gradient in PyTorch is calculated using Scalers'

In [18]:
"""Use of Optimizer.zero_grad()"""

from torch.optim import SGD

X = torch.tensor([2.0,3.34], requires_grad=True)
optimizer = SGD([X],lr = 0.1)

y = (X**2).sum()

y.backward()

print("Gradient before Zero_grad",X.grad)


Gradient before Zero_grad tensor([4.0000, 6.6800])


In [17]:
#optimizer.step() #update all parameters
optimizer.zero_grad()
print("Gradient after zero_grad",X.grad)

Gradient after zero_grad None


In [24]:
"""Use of detach"""

X = torch.tensor([2.34,4.81],requires_grad=True)
y = X**3
z = y.detach()

print(y,z)

tensor([ 12.8129, 111.2846], grad_fn=<PowBackward0>) tensor([ 12.8129, 111.2846])


In [26]:
w = z + 5
print(w)

tensor([ 17.8129, 116.2846])


In [29]:
print("Requires grad for x:",X.requires_grad)
print("Requires grad for y:",y.requires_grad)
print("Requires grad for z:",z.requires_grad)
print("Requires grad for w:",w.requires_grad)

Requires grad for x: True
Requires grad for y: True
Requires grad for z: False
Requires grad for w: False


In [37]:
"""Use of retain_graph"""

x = torch.tensor([3.0,4.12],requires_grad = True)
y = x**3

print(y)

tensor([27.0000, 69.9345], grad_fn=<PowBackward0>)


In [40]:
z = y.sum()
z.backward(retain_graph=True)
print("Gradient dy/dx",x.grad)

Gradient dy/dx tensor([ 81.0000, 152.7696])


In [41]:
x.grad.zero_() #sets the previously calculated gradients to zero
z.backward()
print("second derivative d^2y/dx2",x.grad)

second derivative d^2y/dx2 tensor([27.0000, 50.9232])


In [42]:
"""Exercise Question"""
x = torch.tensor([[2.13,2.34,68.21],[21.9,90.321,71.0]],requires_grad=True)
y = x**3 + 2*x**2 - x
print(y)

tensor([[1.6607e+01, 2.1424e+01, 3.2659e+05],
        [1.1441e+04, 7.5305e+05, 3.6792e+05]], grad_fn=<SubBackward0>)


In [46]:
z = y.sum() + 10
print(z)

tensor(1459055.5000, grad_fn=<AddBackward0>)


In [47]:
z.backward(retain_graph=True)
print("Gradient dy/dx",x.grad)

Gradient dy/dx tensor([[6.3392e+01, 7.4360e+01, 4.2689e+04],
        [4.5763e+03, 7.4502e+04, 4.6218e+04]])
