In [1]:
import torch
import torch.nn as nn

In [8]:
class CustomModel(nn.Module):
    def __init__(self, input_size,hidden_size,output_size):
        super(CustomModel, self).__init__()

        self.fc1 = nn.Linear(input_size,hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size,output_size)

    def forward(self,x):
        x = self.fc1(x)    
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [9]:
model = CustomModel(input_size=10, hidden_size=20, output_size=1)
example_input = torch.rand(5,10)
output = model(example_input)

In [11]:
print(output)

tensor([[0.2425],
        [0.2261],
        [0.2473],
        [0.2169],
        [0.2384]], grad_fn=<AddmmBackward0>)


In [4]:
#Linear Layer
linear = nn.Linear(in_features = 10,out_features = 5)
input = torch.randn(3,10)
output = linear(input)
print(f'Linear layer output shape: { output.shape}')
print(output)
print(input)

Linear layer output shape: torch.Size([3, 5])
tensor([[ 0.6783, -0.2610, -0.5819,  0.5647, -0.4641],
        [ 0.8151, -0.1154,  0.4278,  0.4643, -0.6384],
        [-0.7123, -0.4470,  0.6692, -0.1928, -1.3703]],
       grad_fn=<AddmmBackward0>)
tensor([[-1.3455, -0.3671,  1.1711, -0.2846, -0.0860,  0.4851,  1.1376, -0.8601,
         -0.9491,  0.1943],
        [ 0.3307,  1.9745,  0.2175, -0.8470,  0.3009,  1.1676,  0.2371,  0.5839,
          0.3851, -2.7478],
        [ 1.3860,  0.7465, -0.0153, -0.5678,  2.8607,  0.7468,  0.2005,  0.1278,
         -2.5450,  1.0707]])


In [5]:
print(linear)

Linear(in_features=10, out_features=5, bias=True)


In [34]:
#Convolutional Layer
conv1d = nn.Conv1d(in_channels = 4,out_channels = 8,kernel_size = 3)
input = torch.randn(2, 4, 10)

output = conv1d(input)
print(f'Conv1d output shape: {output.shape}')

Conv1d output shape: torch.Size([2, 8, 8])


In [35]:
class Conv1DModel(nn.Module):
    def __init__(self):
        super(Conv1DModel,self).__init__()
        self.conv1d = nn.Conv1d(in_channels = 4,
        out_channels = 8,kernel_size = 3)

        def forward(self,x):
            x = self.conv1d(x)
            return x

In [33]:
input_tensor = torch.randn(2,4,10)
model = Conv1DModel()
output_tensor = model(input_tensor)

print(output_tensor)


tensor([[[-0.0664, -0.4032, -0.7565, -0.2504, -0.4786,  0.2583, -0.6346,
          -1.1040],
         [ 0.3551, -0.1044,  0.4661, -0.1834,  0.2965,  1.9489,  0.6842,
           0.3986],
         [ 0.0533,  0.3387,  0.2278,  0.2226,  0.1088, -0.4555,  0.4026,
           0.1636],
         [-0.1535, -0.8992, -0.5656, -0.8650, -0.3265, -0.6561, -1.6292,
          -0.6727],
         [ 0.0227, -0.2579, -0.3620, -0.3866, -0.8852,  0.2190, -0.0986,
           0.5537],
         [ 0.3183,  0.7657, -0.1599,  0.6202, -0.9609,  0.3732, -0.6928,
          -0.8073],
         [-1.0228,  0.0030, -0.4160,  0.3563,  0.0112, -0.0808,  0.0619,
          -0.2472],
         [ 0.7283, -0.0979,  0.4784, -0.2307,  1.1259, -0.2382, -1.8045,
          -0.5070]],

        [[-0.3434,  0.9303,  0.5438, -0.1857, -0.1912, -0.4567,  0.5719,
           1.1304],
         [-1.0103, -0.1623,  0.2143,  0.2757,  0.4245, -0.2410, -1.0461,
          -0.2327],
         [-0.0556,  0.7745,  0.3468, -0.5527, -0.6332, -0.6312,  0.1

In [40]:
#MaxPooling
pool = nn.MaxPool2d(kernel_size = 2,stride = 2)
input = torch.randn(1,3,8,8)
output = pool(input)
print(output.shape)


torch.Size([1, 3, 4, 4])


In [38]:
#AdaptivePooling
adap_pool = nn.AdaptiveAvgPool2d((1,1))
input = torch.randn(2,13,28,28)
out = adap_pool(input)
print(output.shape)

torch.Size([1, 3, 4, 4])


In [44]:
#LSTM
lstm = nn.LSTM(input_size = 10,hidden_size = 20,num_layers = 2)
inp_seq = torch.randn(5,3,10)

ho = torch.randn(2,3,20)

co = torch.randn(2,3,20)
output, (ho,co) = lstm(inp_seq,(ho,co))
print(output.shape)
print(output)

torch.Size([5, 3, 20])
tensor([[[ 0.1774,  0.5713,  0.2211,  0.4523, -0.2708, -0.1027, -0.0915,
          -0.1152, -0.2256,  0.2872,  0.0705, -0.2821, -0.2335, -0.0925,
           0.2727, -0.2004,  0.0352,  0.4005, -0.0733, -0.1217],
         [ 0.3629, -0.3504,  0.4153, -0.0232, -0.1214,  0.0812, -0.1560,
          -0.0479,  0.6162, -0.1182, -0.4909,  0.1877, -0.1906, -0.2123,
           0.3481,  0.1309,  0.0488, -0.0844,  0.2475,  0.0508],
         [ 0.0057, -0.5791,  0.3520, -0.1079,  0.2332, -0.1891, -0.1559,
          -0.1320,  0.2642, -0.2227,  0.1889,  0.2030, -0.3330,  0.2293,
           0.3269, -0.1241,  0.1653, -0.4509,  0.2821,  0.1670]],

        [[ 0.0984,  0.3015,  0.2510,  0.2133, -0.2737, -0.0459,  0.0452,
          -0.0629, -0.2754,  0.1409,  0.1619, -0.1978, -0.0574,  0.0263,
           0.1184, -0.1506, -0.0908,  0.2376,  0.0155, -0.0994],
         [ 0.1830, -0.4847,  0.3111, -0.0293, -0.1618, -0.0610, -0.1165,
          -0.0724,  0.2067, -0.0354, -0.1113,  0.1354, -0.

In [49]:
class LSTModel(nn.Module):
    def __init__(self,input_size,hidden_size,num_layers,output_size):
        super(LSTModel).__init__()

        self.lstm = nn.LSTM(input_size = input_size,hidden_size = hidden_size,num_layers = num_layers,batch_first = True)
        self.fc = nn.Linear(hidden_size,output_size)

    def forward(self,x):
        lstm_out,(hidden_state,cell_state) = self.lstm(x)
        out = self.fc(hidden_state[-1])
        return out

In [50]:
input_size = 10
model = LSTModel(10,20,2,1)
x = torch.randn(3,5,input_size)

output = model(x)
print(output)

AttributeError: cannot assign module before Module.__init__() call