In [1]:
import torch

In [2]:
print(torch.__version__)
print("Entry to torch")


print(torch.cuda.is_available())  # For ROCm, this also applies to AMD GPUs
print(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

s = torch.tensor(7)

print(s.ndim, s.item(), s)
print(" ")

v = torch.tensor([7, 7])
print(v,v.ndim,v.shape)


print(" ")
M = torch.tensor([[7,8],[3,4]])
print(M.ndim,M.shape)

T = torch.tensor([[[1, 2, 3], [23, 45, 89], [12, 54, 65]]])
print(T.ndim,T.shape)

2.3.1+cpu
Entry to torch
False
cpu
0 7 tensor(7)
 
tensor([7, 7]) 1 torch.Size([2])
 
2 torch.Size([2, 2])
3 torch.Size([1, 3, 3])


In [3]:
rt=torch.rand(size=(3, 4))
print(rt)
print(rt.dtype)

z = torch.zeros(size=(3, 4))
print(z)
print(z.dtype)

o = torch.ones(size=(5, 4))
print(o)
print(o.dtype)

tensor([[0.8587, 0.2096, 0.3134, 0.3261],
        [0.4630, 0.4337, 0.2894, 0.9881],
        [0.3275, 0.5015, 0.4438, 0.8936]])
torch.float32
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


RANGE

In [14]:
r1 = torch.arange(start = 1,end = 10,step = 2)
r2 = torch.arange(start = 3,end = 12,step = 2)
r1


tensor([1, 3, 5, 7, 9])

In [13]:
print(r2)

tensor([ 3,  5,  7,  9, 11])


In [36]:
zt = torch.cat((r1,r2))
zt

tensor([ 1,  3,  5,  7,  9,  3,  5,  7,  9, 11])

In [37]:
torch.multiply(zt,3.14156143) - 10 + 12

tensor([ 5.1416, 11.4247, 17.7078, 23.9909, 30.2741, 11.4247, 17.7078, 23.9909,
        30.2741, 36.5572])

In [42]:
zt.shape
zt = zt.type(torch.float32)
zt.dtype


torch.float32

In [57]:
k = torch.ones_like(input = zt)
k.dtype
k.shape

torch.Size([10])

In [62]:
w = torch.matmul(zt,k)
print(w + 10)
w.device
w

tensor(70.)


tensor(60.)

In [67]:
print(k,"*",k)
print(w*k) 

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) * tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([60., 60., 60., 60., 60., 60., 60., 60., 60., 60.])


In [53]:
zt.shape

torch.Size([10])

In [59]:
p = zt*k
p

tensor([ 1.,  3.,  5.,  7.,  9.,  3.,  5.,  7.,  9., 11.])

In [70]:
tensorA = torch.tensor([[1,2],[3,4],[4,5]])
tensorA.shape

torch.Size([3, 2])

In [74]:
tensorB = torch.tensor([[34,5],[4,90],[21,41]])
tensorB.shape

torch.Size([3, 2])

In [73]:
torch.mm(tensorA,tensorB.T)

tensor([[ 44, 184, 103],
        [122, 372, 227],
        [161, 466, 289]])

In [80]:
tensorA.dtype

torch.int64

In [81]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,out_features=6)



In [83]:
"""x = tensorA
output = linear(x)
print(x.shape)
print(output.shape)"""

'x = tensorA\noutput = linear(x)\nprint(x.shape)\nprint(output.shape)'

In [88]:
tensor = torch.arange(1,10,2)

In [89]:
tensor.argmax()

tensor(4)

In [87]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [90]:
tensorf16 = tensor.type(torch.float16)

In [91]:
tensorf16.dtype

torch.float16

In [98]:
t = torch.arange(1.,8.)
t.shape
k = t.reshape(1,7)
k.shape

torch.Size([1, 7])

In [99]:
z[:,0] = 5
z,x

(tensor([[5., 0., 0., 0.],
         [5., 0., 0., 0.],
         [5., 0., 0., 0.]]),
 tensor([[1, 2],
         [3, 4],
         [4, 5]]))

In [ ]:
x

In [102]:
x_s = torch.stack([x,x,x,x])
x_s

tensor([[[1, 2],
         [3, 4],
         [4, 5]],

        [[1, 2],
         [3, 4],
         [4, 5]],

        [[1, 2],
         [3, 4],
         [4, 5]],

        [[1, 2],
         [3, 4],
         [4, 5]]])

In [105]:
x_se = x_s.squeeze()
x_se.shape,x_s.shape

(torch.Size([4, 3, 2]), torch.Size([4, 3, 2]))

In [111]:
q = torch.arange(1,10).reshape(1,3,3)
q[0][1][2]

tensor(6)